### ISSUE TITLE
Is anyone willing to maintain this for the long term? The author seems to have given up

### ISSUE THREAD

**Issue by Smalldy** [progschj/ThreadPool#97]
Is anyone willing to maintain this for the long term? The author seems to have given up

**Comment by wolframroesler** [comment]
Or just gone on vacation for a while. Patience is a virtue. FWIW, if you're looking for a cmake file you can have a look at my fork, which also comes with a demo program and some more documentation (which I wrote for a talk I did some time ago): https://github.com/wolframroesler/ThreadPool

**Comment by progschj** [comment]
I guess I am neglecting this but. But the reason why I don't "maintain" it is because there isn't much to maintain in my opinion. It does what it was meant to do at the time (be a minimal C++11 threadpool to base stuff on). Some of the C++17 issues (`result_of`) are a bit awkward since they are the "correct" thing to do in C++11 but then got deprecated later.

I never added or merged any features because the whole point of this repo to me was to have a baseline with minimal functionality that would be easy to add on to.
